name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_UPDATED_DATE: "True"
          SHOW_LINES_OF_CODE: "True"
          IGNORED_REPOS: "asdb, mypro, newprojects, myprojects, age-calc, colorgenerator, basic, sample, test, cfs, abcd, cfs-history-17-jan-2023, concord, testing, ebmpapst, bulgin, subhas, carlogavazzi, adityatest1, instockav6, testing14, instockav5, instockav4, microtest1, cotek, instockav3, synctest, draftlogin1, draftlogin, test122, asdb, mypro, newprojects, myprojects, age-calc, colorgenerator, basic, sample, test, cfs, abcd, cfs-history-17-jan-2023, concord, testing, ebmpapst, bulgin, subhas, carlogavazzi, adityatest1, instockav6, testing14, instockav5, instockav4, microtest1, cotek, instockav3, synctest, draftlogin1, draftlogin, test122"